export interface BoardingSchool {
  id: string;
  name: string;
  location: string;
  city: string;
  state: string;
  yearEstablished: number;
  type: "Boarding" | "Day Boarding";
  curriculum: string[];
  grades: string;
  annualFees: {
    min: number;
    max: number;
  };
  indoorSports: string[];
  outdoorSports: string[];
  rating: number;
  reviews: number;
  imageUrl: string;
  description: string;
  facilities: string[];
  aboutSchool: string;
  studentCapacity?: number;
  teacherStudentRatio?: string;
  website?: string;
  contact?: string;
  tourImages?: string[];
  detailedDescription?: string;
}

export const boardingSchools: BoardingSchool[] = [
  {
    id: "1",
    name: "ECOLE GLOBALE INTERNATIONAL GIRLS SCHOOL",
    location: "Sahaspur Road, Horawala, Uttarakhand",
    city: "Dehradun",
    state: "Uttarakhand",
    yearEstablished: 2003,
    type: "Boarding",
    curriculum: ["CBSE", "CIE"],
    grades: "4-12",
    annualFees: {
      min: 700000,
      max: 1000000,
    },
    indoorSports: ["Swimming", "Martial Arts"],
    outdoorSports: ["Basketball", "Athletics", "Squash", "Shooting", "Horse Riding"],
    rating: 4.5,
    reviews: 619,
    imageUrl: "/schools/ecole-globale-boarding-school-in-india.jpg.webp",
    description: "Premier girls boarding school in Dehradun with world-class facilities and empowerment-focused curriculum.",
    facilities: ["Modern Classrooms", "Well-equipped Laboratories", "Sports Facilities", "Library", "Hostel Facilities", "Medical Center"],
    aboutSchool: "Ecole Globale has been a leader in girls education with focus on empowerment, leadership, and professionalism.",
    studentCapacity: 400,
    teacherStudentRatio: "1:12",
    website: "https://www.ecoleglobale.edu.in",
    contact: "+91-135-2741234",
    detailedDescription: "Ecole Globale International Girls School is one of the premier boarding institutions for girls in India.",
    tourImages: [
      "/schools/ecole-globale-boarding-school-in-india.jpg.webp",
      "/schools/bishop-cotton-school.jpg.webp",
      "/schools/the-doon-school.jpg.webp",
      "/schools/CANADIAN-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/KODAIKANAL-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/Welham-Girls-School-in-india.jpg.webp",
    ],
  },
  {
    id: "2",
    name: "THE DOON SCHOOL",
    location: "Mall Rd, Krishna Nagar, Dehradun",
    city: "Dehradun",
    state: "Uttarakhand",
    yearEstablished: 1935,
    type: "Boarding",
    curriculum: ["IB", "CISCE", "IGCSE"],
    grades: "7-12",
    annualFees: {
      min: 1025000,
      max: 1025000,
    },
    indoorSports: ["Table Tennis", "Chess"],
    outdoorSports: ["Basketball", "Volleyball", "Cricket"],
    rating: 4.3,
    reviews: 685,
    imageUrl: "/schools/the-doon-school.jpg.webp",
    description: "Asia's most prestigious all-boys boarding school established in 1935 with rigorous academics.",
    facilities: ["70-acre Campus", "State-of-the-art Infrastructure", "Sports Facilities", "Library", "Boarding Houses", "Computer Labs"],
    aboutSchool: "Founded in 1935, The Doon School is hailed as the best boarding school in India.",
    studentCapacity: 600,
    teacherStudentRatio: "1:10",
    website: "https://www.doonschool.com",
    contact: "+91-135-2741751",
    detailedDescription: "The Doon School is one of the world's finest boarding institutions, spread across a sprawling 70-acre campus.",
    tourImages: [
      "/schools/the-doon-school.jpg.webp",
      "/schools/bishop-cotton-school.jpg.webp",
      "/schools/THE-LAWRENCE-SCHOOL.jpg.webp",
      "/schools/HEBRON-SCHOOL.jpg.webp",
      "/schools/WOODSTOCK-SCHOOL.jpg.webp",
      "/schools/ecole-globale-boarding-school-in-india.jpg.webp",
    ],
  },
  {
    id: "3",
    name: "BISHOP COTTON SCHOOL",
    location: "Shimla Bypass, Khalini, Shimla",
    city: "Shimla",
    state: "Himachal Pradesh",
    yearEstablished: 1859,
    type: "Boarding",
    curriculum: ["ICSE", "ISC"],
    grades: "3-12",
    annualFees: {
      min: 530000,
      max: 565000,
    },
    indoorSports: ["Table Tennis", "Chess"],
    outdoorSports: ["Cricket", "Football", "Athletics"],
    rating: 4.4,
    reviews: 270,
    imageUrl: "/schools/bishop-cotton-school.jpg.webp",
    description: "One of Asia's oldest and most beautiful boys boarding schools with focus on character-building.",
    facilities: ["Modern Classrooms", "Science Labs", "Library", "Sports Grounds", "Boarding Houses", "Computer Center"],
    aboutSchool: "Founded in 1859, Bishop Cotton School is one of the oldest and most beautiful boys boarding schools in Asia.",
    website: "https://www.bishopcoltonschool.com",
    contact: "+91-177-2805000",
    detailedDescription: "Bishop Cotton School sits majestically on the Shimla Hills, offering a unique blend of heritage and modernity.",
    tourImages: [
      "/schools/bishop-cotton-school.jpg.webp",
      "/schools/the-doon-school.jpg.webp",
      "/schools/THE-LAWRENCE-SCHOOL.jpg.webp",
      "/schools/HEBRON-SCHOOL.jpg.webp",
      "/schools/WOODSTOCK-SCHOOL.jpg.webp",
      "/schools/ecole-globale-boarding-school-in-india.jpg.webp",
    ],
  },
  {
    id: "4",
    name: "WELHAM GIRLS SCHOOL",
    location: "19 Municipal Rd, Dalanwala, Dehradun",
    city: "Dehradun",
    state: "Uttarakhand",
    yearEstablished: 1957,
    type: "Boarding",
    curriculum: ["ICSE", "ISC"],
    grades: "5-12",
    annualFees: {
      min: 675000,
      max: 675000,
    },
    indoorSports: ["Dance", "Music"],
    outdoorSports: ["Basketball", "Volleyball", "Sports"],
    rating: 4.3,
    reviews: 228,
    imageUrl: "/schools/Welham-Girls-School-in-india.jpg.webp",
    description: "Premier girls boarding school ranked among the top in India with focus on excellence.",
    facilities: ["Modern Facilities", "Sports Amenities", "Creative Outlets", "Library", "Laboratories", "Community Center"],
    aboutSchool: "Established in 1957, Welham Girls School is ranked among the top girls boarding schools in India.",
    website: "https://www.welhambschool.com",
    contact: "+91-135-2740123",
    detailedDescription: "Welham Girls School provides an excellent education that prepares girls to be confident and accomplished.",
    tourImages: [
      "/schools/Welham-Girls-School-in-india.jpg.webp",
      "/schools/ecole-globale-boarding-school-in-india.jpg.webp",
      "/schools/KODAIKANAL-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/RISHI-VALLEY-SCHOOL-1.jpg.webp",
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/the-doon-school.jpg.webp",
    ],
  },
  {
    id: "5",
    name: "MAYO COLLEGE",
    location: "Shrinagar Rd, Ajmer, Rajasthan",
    city: "Ajmer",
    state: "Rajasthan",
    yearEstablished: 1875,
    type: "Boarding",
    curriculum: ["CBSE"],
    grades: "4-12",
    annualFees: {
      min: 650000,
      max: 650000,
    },
    indoorSports: ["Chess", "Table Tennis"],
    outdoorSports: ["Basketball", "Volleyball", "Cricket", "Football"],
    rating: 4.4,
    reviews: 385,
    imageUrl: "/schools/MAYO-COLLEGE.jpg.webp",
    description: "One of India's oldest public boarding schools established in 1875 with dual curriculum.",
    facilities: ["187 acres Campus", "40-bed Infirmary", "Library with 41,000+ books", "Sports Infrastructure", "Laboratories", "Computer Center"],
    aboutSchool: "Established in 1875, Mayo College is one of India's oldest public boarding schools.",
    website: "https://www.mayocollege.com",
    contact: "+91-145-2425000",
    detailedDescription: "Mayo College is a legacy institution established over 140 years ago with expansive 187-acre campus.",
    tourImages: [
      "/schools/MAYO-COLLEGE.jpg.webp",
      "/schools/bishop-cotton-school.jpg.webp",
      "/schools/WOODSTOCK-SCHOOL.jpg.webp",
      "/schools/THE-LAWRENCE-SCHOOL.jpg.webp",
      "/schools/HEBRON-SCHOOL.jpg.webp",
      "/schools/the-doon-school.jpg.webp",
    ],
  },
  {
    id: "6",
    name: "CANADIAN INTERNATIONAL SCHOOL",
    location: "Sector 39A, Faridabad",
    city: "Faridabad",
    state: "Haryana",
    yearEstablished: 2008,
    type: "Boarding",
    curriculum: ["IB", "IGCSE"],
    grades: "KG-12",
    annualFees: {
      min: 900000,
      max: 1200000,
    },
    indoorSports: ["Swimming", "Basketball"],
    outdoorSports: ["Cricket", "Football", "Athletics", "Tennis"],
    rating: 4.2,
    reviews: 450,
    imageUrl: "/schools/CANADIAN-INTERNATIONAL-SCHOOL.jpg.webp",
    description: "International school with Canadian curriculum and modern facilities in NCR region.",
    facilities: ["World-class Labs", "Olympic-size Pool", "State-of-the-art Facilities", "Sports Complex", "Auditorium", "Art Studios"],
    aboutSchool: "Canadian International School provides world-class education following Canadian curriculum standards.",
    studentCapacity: 850,
    teacherStudentRatio: "1:15",
    website: "https://www.cisdelhi.org",
    contact: "+91-129-4091100",
    detailedDescription: "A premier international school offering Canadian and IB curriculum with modern infrastructure.",
    tourImages: [
      "/schools/CANADIAN-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/THE-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/THE-ASIAN-SCHOOL.jpg.webp",
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
    ],
  },
  {
    id: "7",
    name: "CANDOR INTERNATIONAL SCHOOL",
    location: "Airoli, Navi Mumbai",
    city: "Navi Mumbai",
    state: "Maharashtra",
    yearEstablished: 2010,
    type: "Boarding",
    curriculum: ["IB", "CBSE"],
    grades: "KG-12",
    annualFees: {
      min: 850000,
      max: 1100000,
    },
    indoorSports: ["Karate", "Gymnastics"],
    outdoorSports: ["Cricket", "Football", "Hockey", "Basketball"],
    rating: 4.3,
    reviews: 520,
    imageUrl: "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
    description: "Modern international school with IB curriculum and contemporary facilities in Mumbai.",
    facilities: ["Innovation Lab", "Digital Classrooms", "Olympic-size Pool", "Sports Fields", "Theater", "Science Centers"],
    aboutSchool: "Candor International School is a world-class institution offering holistic development.",
    studentCapacity: 950,
    teacherStudentRatio: "1:14",
    website: "https://www.candor.edu.in",
    contact: "+91-22-61651000",
    detailedDescription: "Premier international school in Mumbai with modern infrastructure and IB programs.",
    tourImages: [
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/CANADIAN-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/THE-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
      "/schools/SREENIDHI-INTERNATIONAL-SCHOOL.jpg.webp",
    ],
  },
  {
    id: "8",
    name: "GOOD SHEPHERD INTERNATIONAL SCHOOL",
    location: "Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    yearEstablished: 1997,
    type: "Boarding",
    curriculum: ["IB", "IGCSE"],
    grades: "Nursery-12",
    annualFees: {
      min: 780000,
      max: 950000,
    },
    indoorSports: ["Swimming", "Badminton"],
    outdoorSports: ["Cricket", "Hockey", "Football", "Tennis"],
    rating: 4.4,
    reviews: 680,
    imageUrl: "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
    description: "Leading international school in Bangalore with IB and IGCSE curriculum.",
    facilities: ["State-of-the-art Labs", "Indoor Pool", "Comprehensive Sports Complex", "Library", "Music Studio", "Art Center"],
    aboutSchool: "Good Shepherd International School is a leading institution for holistic education.",
    studentCapacity: 1200,
    teacherStudentRatio: "1:13",
    website: "https://www.gsis.edu.in",
    contact: "+91-80-27838000",
    detailedDescription: "Bangalore's premier international school with focus on academic excellence and character building.",
    tourImages: [
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/KODAIKANAL-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/RISHI-VALLEY-SCHOOL-1.jpg.webp",
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/SREENIDHI-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/bishop-cotton-school.jpg.webp",
    ],
  },
  {
    id: "9",
    name: "HEBRON SCHOOL",
    location: "Ooty Road, Coonoor",
    city: "Nilgiris",
    state: "Tamil Nadu",
    yearEstablished: 1873,
    type: "Boarding",
    curriculum: ["ICSE", "ISC"],
    grades: "3-12",
    annualFees: {
      min: 650000,
      max: 750000,
    },
    indoorSports: ["Table Tennis", "Badminton"],
    outdoorSports: ["Cricket", "Football", "Cross Country"],
    rating: 4.5,
    reviews: 410,
    imageUrl: "/schools/HEBRON-SCHOOL.jpg.webp",
    description: "Historic boarding school in Nilgiris with ICSE curriculum and heritage campus.",
    facilities: ["Well-stocked Library", "Science Labs", "Sports Complex", "Playground", "Art Studio", "Music Hall"],
    aboutSchool: "Founded in 1873, Hebron School is one of India's oldest boarding institutions.",
    studentCapacity: 550,
    teacherStudentRatio: "1:11",
    website: "https://www.hebronschool.in",
    contact: "+91-423-2433234",
    detailedDescription: "Hebron School is a heritage institution located in the Nilgiri Mountains with excellent academics.",
    tourImages: [
      "/schools/HEBRON-SCHOOL.jpg.webp",
      "/schools/KODAIKANAL-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/bishop-cotton-school.jpg.webp",
      "/schools/WOODSTOCK-SCHOOL.jpg.webp",
      "/schools/THE-LAWRENCE-SCHOOL.jpg.webp",
      "/schools/RISHI-VALLEY-SCHOOL-1.jpg.webp",
    ],
  },
  {
    id: "10",
    name: "JAIN INTERNATIONAL RESIDENTIAL SCHOOL",
    location: "Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    yearEstablished: 2009,
    type: "Boarding",
    curriculum: ["IB", "CBSE"],
    grades: "KG-12",
    annualFees: {
      min: 900000,
      max: 1150000,
    },
    indoorSports: ["Squash", "Swimming"],
    outdoorSports: ["Cricket", "Football", "Basketball", "Tennis"],
    rating: 4.2,
    reviews: 390,
    imageUrl: "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
    description: "Premium residential school in Mumbai with IB curriculum and world-class infrastructure.",
    facilities: ["High-tech Labs", "Olympic Pool", "Residential Campus", "Sports Facilities", "Theater", "Innovation Hub"],
    aboutSchool: "Jain School provides exceptional education with focus on innovation and global perspective.",
    studentCapacity: 800,
    teacherStudentRatio: "1:12",
    website: "https://www.jirs.edu.in",
    contact: "+91-22-61000000",
    detailedDescription: "Premium residential school offering IB curriculum with modern campus facilities.",
    tourImages: [
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/THE-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/SREENIDHI-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/CANADIAN-INTERNATIONAL-SCHOOL.jpg.webp",
    ],
  },
  {
    id: "11",
    name: "KODAIKANAL INTERNATIONAL SCHOOL",
    location: "Kodaikanal, Tamil Nadu",
    city: "Kodaikanal",
    state: "Tamil Nadu",
    yearEstablished: 1901,
    type: "Boarding",
    curriculum: ["IB", "IGCSE"],
    grades: "KG-12",
    annualFees: {
      min: 850000,
      max: 1000000,
    },
    indoorSports: ["Swimming", "Table Tennis"],
    outdoorSports: ["Cricket", "Horse Riding", "Rock Climbing", "Orienteering"],
    rating: 4.6,
    reviews: 520,
    imageUrl: "/schools/KODAIKANAL-INTERNATIONAL-SCHOOL.jpg.webp",
    description: "Prestigious boarding school in Kodaikanal with IB and IGCSE curriculum.",
    facilities: ["Well-equipped Labs", "Olympic Pool", "Adventure Center", "Riding Stables", "Library", "Sports Complex"],
    aboutSchool: "Kodaikanal International is a leading boarding school with world-class facilities.",
    studentCapacity: 700,
    teacherStudentRatio: "1:11",
    website: "https://www.kis.in",
    contact: "+91-452-2241000",
    detailedDescription: "Historic boarding school in the Nilgiris offering IB curriculum with exceptional facilities.",
    tourImages: [
      "/schools/KODAIKANAL-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/HEBRON-SCHOOL.jpg.webp",
      "/schools/WOODSTOCK-SCHOOL.jpg.webp",
      "/schools/RISHI-VALLEY-SCHOOL-1.jpg.webp",
      "/schools/bishop-cotton-school.jpg.webp",
      "/schools/Welham-Girls-School-in-india.jpg.webp",
    ],
  },
  {
    id: "12",
    name: "RISHI VALLEY SCHOOL",
    location: "Rishi Valley, Andhra Pradesh",
    city: "Madanapalle",
    state: "Andhra Pradesh",
    yearEstablished: 1926,
    type: "Boarding",
    curriculum: ["IB", "ICSE"],
    grades: "3-12",
    annualFees: {
      min: 550000,
      max: 700000,
    },
    indoorSports: ["Martial Arts", "Yoga"],
    outdoorSports: ["Cricket", "Basketball", "Football", "Badminton"],
    rating: 4.5,
    reviews: 480,
    imageUrl: "/schools/RISHI-VALLEY-SCHOOL-1.jpg.webp",
    description: "Holistic boarding school established in 1926 with focus on all-round development.",
    facilities: ["Organic Farm", "Science Labs", "Library", "Sports Grounds", "Art Studios", "Meditation Center"],
    aboutSchool: "Rishi Valley School provides education emphasizing values and holistic growth.",
    studentCapacity: 600,
    teacherStudentRatio: "1:10",
    website: "https://www.rishivalley.org",
    contact: "+91-877-2242211",
    detailedDescription: "Established in 1926, Rishi Valley is a leading boarding school known for holistic education.",
    tourImages: [
      "/schools/RISHI-VALLEY-SCHOOL-1.jpg.webp",
      "/schools/Welham-Girls-School-in-india.jpg.webp",
      "/schools/KODAIKANAL-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/SREENIDHI-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/ecole-globale-boarding-school-in-india.jpg.webp",
    ],
  },
  {
    id: "13",
    name: "SHAYADRI SCHOOL",
    location: "Purandhar, Pune",
    city: "Pune",
    state: "Maharashtra",
    yearEstablished: 1993,
    type: "Boarding",
    curriculum: ["IB", "IGCSE"],
    grades: "6-12",
    annualFees: {
      min: 650000,
      max: 850000,
    },
    indoorSports: ["Swimming", "Basketball"],
    outdoorSports: ["Cricket", "Football", "Volleyball", "Badminton"],
    rating: 4.3,
    reviews: 380,
    imageUrl: "/schools/SHAYADRI-SCHOOL.jpg.webp",
    description: "Modern boarding school in Pune with IB and IGCSE curriculum.",
    facilities: ["Science Blocks", "Sports Complex", "Library", "IT Labs", "Adventure Center", "Hostel Facilities"],
    aboutSchool: "Shayadri School offers comprehensive education with modern facilities.",
    studentCapacity: 650,
    teacherStudentRatio: "1:14",
    website: "https://www.shayadrischool.org",
    contact: "+91-2138-329000",
    detailedDescription: "Located near Pune, Shayadri School offers IB curriculum with modern infrastructure.",
    tourImages: [
      "/schools/SHAYADRI-SCHOOL.jpg.webp",
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
      "/schools/SREENIDHI-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/WOODSTOCK-SCHOOL.jpg.webp",
    ],
  },
  {
    id: "14",
    name: "SREENIDHI INTERNATIONAL SCHOOL",
    location: "Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    yearEstablished: 2008,
    type: "Boarding",
    curriculum: ["IB", "CBSE"],
    grades: "KG-12",
    annualFees: {
      min: 700000,
      max: 950000,
    },
    indoorSports: ["Swimming", "Badminton"],
    outdoorSports: ["Cricket", "Football", "Basketball", "Volleyball"],
    rating: 4.2,
    reviews: 410,
    imageUrl: "/schools/SREENIDHI-INTERNATIONAL-SCHOOL.jpg.webp",
    description: "International school in Hyderabad with IB curriculum and modern campus.",
    facilities: ["State-of-the-art Labs", "Olympic Pool", "Sports Complex", "Library", "Art Center", "Music Studio"],
    aboutSchool: "Sreenidhi International School provides world-class education and holistic development.",
    studentCapacity: 900,
    teacherStudentRatio: "1:13",
    website: "https://www.sreenidhi.edu.in",
    contact: "+91-40-69299999",
    detailedDescription: "Leading international school in Hyderabad with comprehensive IB curriculum.",
    tourImages: [
      "/schools/SREENIDHI-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
      "/schools/SHAYADRI-SCHOOL.jpg.webp",
      "/schools/RISHI-VALLEY-SCHOOL-1.jpg.webp",
    ],
  },
  {
    id: "15",
    name: "STONEHILL INTERNATIONAL SCHOOL",
    location: "Talegaon, Pune",
    city: "Talegaon",
    state: "Maharashtra",
    yearEstablished: 2012,
    type: "Boarding",
    curriculum: ["IB", "IGCSE"],
    grades: "Nursery-12",
    annualFees: {
      min: 850000,
      max: 1100000,
    },
    indoorSports: ["Swimming", "Martial Arts"],
    outdoorSports: ["Cricket", "Football", "Horse Riding", "Adventure Sports"],
    rating: 4.1,
    reviews: 320,
    imageUrl: "/schools/STONEHILL-INTERNATIONAL-SCHOOL.jpg.webp",
    description: "Premium international school near Pune with IB curriculum and adventure focus.",
    facilities: ["Advanced Labs", "Adventure Park", "Equestrian Center", "Olympic Pool", "Sports Fields", "Art Studios"],
    aboutSchool: "Stonehill International provides holistic education with emphasis on adventure and innovation.",
    studentCapacity: 700,
    teacherStudentRatio: "1:12",
    website: "https://www.stonehillschool.com",
    contact: "+91-2114-285555",
    detailedDescription: "Stonehill offers IB curriculum with unique focus on adventure and outdoor activities.",
    tourImages: [
      "/schools/STONEHILL-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/SHAYADRI-SCHOOL.jpg.webp",
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/THE-INTERNATIONAL-SCHOOL.jpg.webp",
    ],
  },
  {
    id: "16",
    name: "THE AGA KHAN ACADEMY",
    location: "Delhi",
    city: "Delhi",
    state: "Delhi",
    yearEstablished: 2010,
    type: "Boarding",
    curriculum: ["IB"],
    grades: "Nursery-12",
    annualFees: {
      min: 1000000,
      max: 1300000,
    },
    indoorSports: ["Swimming", "Squash"],
    outdoorSports: ["Cricket", "Tennis", "Basketball", "Football"],
    rating: 4.6,
    reviews: 650,
    imageUrl: "/schools/THE-AGA-KHAN-ACADEMY.jpg.webp",
    description: "Prestigious international school in Delhi with exclusive IB curriculum.",
    facilities: ["World-class Infrastructure", "Olympic Pool", "Tennis Courts", "Theater", "Digital Labs", "Luxury Hostels"],
    aboutSchool: "Aga Khan Academy offers premium education with IB curriculum and world-class facilities.",
    studentCapacity: 1100,
    teacherStudentRatio: "1:10",
    website: "https://www.akadelhischool.edu.in",
    contact: "+91-11-41831111",
    detailedDescription: "Prestigious academy in Delhi offering exclusive IB curriculum with premium infrastructure.",
    tourImages: [
      "/schools/THE-AGA-KHAN-ACADEMY.jpg.webp",
      "/schools/THE-ASIAN-SCHOOL.jpg.webp",
      "/schools/THE-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/CANADIAN-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
    ],
  },
  {
    id: "17",
    name: "THE ASIAN SCHOOL",
    location: "Gurgaon",
    city: "Gurgaon",
    state: "Haryana",
    yearEstablished: 2003,
    type: "Boarding",
    curriculum: ["IB", "CBSE"],
    grades: "Nursery-12",
    annualFees: {
      min: 750000,
      max: 1050000,
    },
    indoorSports: ["Swimming", "Badminton"],
    outdoorSports: ["Cricket", "Football", "Basketball", "Volleyball"],
    rating: 4.3,
    reviews: 560,
    imageUrl: "/schools/THE-ASIAN-SCHOOL.jpg.webp",
    description: "Leading international school in Gurgaon with IB and CBSE curriculum.",
    facilities: ["Modern Campus", "Sports Complex", "Science Labs", "Library", "Art Center", "Design Studio"],
    aboutSchool: "The Asian School provides contemporary education with focus on creativity and innovation.",
    studentCapacity: 1300,
    teacherStudentRatio: "1:15",
    website: "https://www.theasianschool.org",
    contact: "+91-124-4517777",
    detailedDescription: "Leading school in Gurgaon offering IB and CBSE curriculum with modern infrastructure.",
    tourImages: [
      "/schools/THE-ASIAN-SCHOOL.jpg.webp",
      "/schools/THE-AGA-KHAN-ACADEMY.jpg.webp",
      "/schools/THE-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/CANADIAN-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
    ],
  },
  {
    id: "18",
    name: "THE INTERNATIONAL SCHOOL",
    location: "Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    yearEstablished: 1996,
    type: "Boarding",
    curriculum: ["IB", "IGCSE"],
    grades: "Nursery-12",
    annualFees: {
      min: 850000,
      max: 1150000,
    },
    indoorSports: ["Swimming", "Table Tennis"],
    outdoorSports: ["Cricket", "Football", "Basketball", "Tennis"],
    rating: 4.4,
    reviews: 610,
    imageUrl: "/schools/THE-INTERNATIONAL-SCHOOL.jpg.webp",
    description: "Prestigious international school in Bangalore with IB and IGCSE curriculum.",
    facilities: ["State-of-the-art Labs", "Olympic Pool", "Theater", "Music Studio", "Art Center", "Sports Complex"],
    aboutSchool: "International School offers comprehensive education with focus on global competence.",
    studentCapacity: 1200,
    teacherStudentRatio: "1:12",
    website: "https://www.tisb.org",
    contact: "+91-80-41135000",
    detailedDescription: "Prestigious school in Bangalore offering IB curriculum with world-class infrastructure.",
    tourImages: [
      "/schools/THE-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/THE-ASIAN-SCHOOL.jpg.webp",
      "/schools/THE-AGA-KHAN-ACADEMY.jpg.webp",
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
    ],
  },
  {
    id: "19",
    name: "THE LAWRENCE SCHOOL",
    location: "Sanawar, Himachal Pradesh",
    city: "Solan",
    state: "Himachal Pradesh",
    yearEstablished: 1847,
    type: "Boarding",
    curriculum: ["ICSE", "ISC"],
    grades: "3-12",
    annualFees: {
      min: 580000,
      max: 680000,
    },
    indoorSports: ["Table Tennis", "Badminton"],
    outdoorSports: ["Cricket", "Football", "Riding", "Squash"],
    rating: 4.5,
    reviews: 390,
    imageUrl: "/schools/THE-LAWRENCE-SCHOOL.jpg.webp",
    description: "Historic boarding school in Himachal Pradesh with ICSE curriculum and heritage campus.",
    facilities: ["Beautiful Campus", "Science Labs", "Sports Complex", "Library", "Art Studio", "Riding Stables"],
    aboutSchool: "Founded in 1847, Lawrence School is one of India's most prestigious boarding institutions.",
    studentCapacity: 650,
    teacherStudentRatio: "1:11",
    website: "https://www.lawrenceschool.edu.in",
    contact: "+91-1792-237711",
    detailedDescription: "Historic school established in 1847 offering ICSE curriculum with heritage campus.",
    tourImages: [
      "/schools/THE-LAWRENCE-SCHOOL.jpg.webp",
      "/schools/bishop-cotton-school.jpg.webp",
      "/schools/HEBRON-SCHOOL.jpg.webp",
      "/schools/WOODSTOCK-SCHOOL.jpg.webp",
      "/schools/the-doon-school.jpg.webp",
      "/schools/MAYO-COLLEGE.jpg.webp",
    ],
  },
  {
    id: "20",
    name: "TRIO WORLD ACADEMY",
    location: "Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    yearEstablished: 2008,
    type: "Boarding",
    curriculum: ["IB", "CBSE"],
    grades: "KG-12",
    annualFees: {
      min: 800000,
      max: 1000000,
    },
    indoorSports: ["Swimming", "Badminton"],
    outdoorSports: ["Cricket", "Football", "Basketball", "Tennis"],
    rating: 4.2,
    reviews: 470,
    imageUrl: "/schools/TRIO-WORLD-ACADEMY.jpg.webp",
    description: "International school in Bangalore offering IB curriculum with modern facilities.",
    facilities: ["Advanced Labs", "Olympics Pool", "Sports Complex", "Design Studio", "Library", "Music Center"],
    aboutSchool: "Trio World Academy provides contemporary education with focus on creativity and innovation.",
    studentCapacity: 950,
    teacherStudentRatio: "1:14",
    website: "https://www.trioworldacademy.com",
    contact: "+91-80-45299999",
    detailedDescription: "International school in Bangalore offering IB curriculum with comprehensive facilities.",
    tourImages: [
      "/schools/TRIO-WORLD-ACADEMY.jpg.webp",
      "/schools/GOOD-SHEPHERD-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/THE-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/SREENIDHI-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/CANDOR-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/JAIN-INTERNATIONAL-RESIDENTIAL-SCHOOL.jpg.webp",
    ],
  },
  {
    id: "21",
    name: "WOODSTOCK SCHOOL",
    location: "Landour, Mussoorie",
    city: "Mussoorie",
    state: "Uttarakhand",
    yearEstablished: 1854,
    type: "Boarding",
    curriculum: ["IB", "IGCSE"],
    grades: "K-12",
    annualFees: {
      min: 850000,
      max: 1050000,
    },
    indoorSports: ["Swimming", "Basketball"],
    outdoorSports: ["Cricket", "Football", "Mountaineering", "Skiing"],
    rating: 4.6,
    reviews: 540,
    imageUrl: "/schools/WOODSTOCK-SCHOOL.jpg.webp",
    description: "Historic boarding school in Mussoorie with IB and IGCSE curriculum.",
    facilities: ["Beautiful Mountain Campus", "Science Labs", "Olympic Pool", "Sports Fields", "Art Studios", "Theater"],
    aboutSchool: "Founded in 1854, Woodstock School provides world-class education in a heritage setting.",
    studentCapacity: 750,
    teacherStudentRatio: "1:10",
    website: "https://www.woodstockschool.in",
    contact: "+91-135-2633111",
    detailedDescription: "Historic school established in 1854 on the foothills offering IB curriculum.",
    tourImages: [
      "/schools/WOODSTOCK-SCHOOL.jpg.webp",
      "/schools/KODAIKANAL-INTERNATIONAL-SCHOOL.jpg.webp",
      "/schools/HEBRON-SCHOOL.jpg.webp",
      "/schools/bishop-cotton-school.jpg.webp",
      "/schools/THE-LAWRENCE-SCHOOL.jpg.webp",
      "/schools/the-doon-school.jpg.webp",
    ],
  },
];
