"use client"

import React, { useState, useMemo } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Calculator } from "lucide-react"
import { boardingSchools } from "@/lib/schools-data"
import { formatCurrency } from "@/lib/utils"

interface CalculationBreakdown {
  annualFee: number
  yearsOfStudy: number
  totalFee: number
  extraActivities: number
  extraSports: number
  grandTotal: number
}

export default function PricingCalculator() {
  const [selectedSchool, setSelectedSchool] = useState<string>(
    boardingSchools[0].id
  )
  const [currentGrade, setCurrentGrade] = useState<string>("9")
  const [targetGrade, setTargetGrade] = useState<string>("12")
  const [extraActivities, setExtraActivities] = useState<string>("0")
  const [extraSports, setExtraSports] = useState<string>("0")

  const calculation = useMemo(() => {
    const school = boardingSchools.find((s) => s.id === selectedSchool)
    if (!school) return null

    const current = parseInt(currentGrade) || 9
    const target = parseInt(targetGrade) || 12
    const yearsOfStudy = Math.max(1, target - current + 1)

    const avgAnnualFee = (school.annualFees.min + school.annualFees.max) / 2
    const annualFee = Math.round(avgAnnualFee * 10000) // Convert to rupees
    const totalFee = annualFee * yearsOfStudy
    const extraActivitiesTotal = parseInt(extraActivities) * yearsOfStudy || 0
    const extraSportsTotal = parseInt(extraSports) * yearsOfStudy || 0
    const grandTotal = totalFee + extraActivitiesTotal + extraSportsTotal

    return {
      annualFee,
      yearsOfStudy,
      totalFee,
      extraActivities: extraActivitiesTotal,
      extraSports: extraSportsTotal,
      grandTotal,
    }
  }, [selectedSchool, currentGrade, targetGrade, extraActivities, extraSports])

  const handleDownload = () => {
    if (!calculation) return
    const school = boardingSchools.find((s) => s.id === selectedSchool)
    const report = `
EDUMINATI SCHOOL COST CALCULATOR REPORT
========================================
School: ${school?.name}
Location: ${school?.city}
Current Grade: ${currentGrade}
Target Grade: ${targetGrade}
Years of Study: ${calculation.yearsOfStudy}

COST BREAKDOWN
==============
Annual Fee: ₹${(calculation.annualFee / 100000).toFixed(2)} L
Total Tuition (${calculation.yearsOfStudy} years): ₹${(calculation.totalFee / 100000).toFixed(2)} L
Extra Activities (${calculation.yearsOfStudy} years): ₹${(calculation.extraActivities / 100000).toFixed(2)} L
Extra Sports (${calculation.yearsOfStudy} years): ₹${(calculation.extraSports / 100000).toFixed(2)} L

GRAND TOTAL: ₹${(calculation.grandTotal / 100000).toFixed(2)} L

Generated by Eduminati Boarding Guide
    `
    const element = document.createElement("a")
    element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(report))
    element.setAttribute("download", `${school?.name}-cost-report.txt`)
    element.style.display = "none"
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  if (!calculation) return null

  return (
    <section className="py-16 md:py-24 bg-white dark:bg-slate-950">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-12">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Calculator className="w-8 h-8 text-blue-600" />
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white">
              School Cost Calculator
            </h2>
          </div>
          <p className="text-lg text-slate-700 dark:text-slate-300">
            Estimate the total cost of boarding school education with this interactive calculator
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          {/* Input Section */}
          <Card>
            <CardHeader>
              <CardTitle>Calculate Your Costs</CardTitle>
              <CardDescription>Enter your details to see detailed cost breakdown</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* School Selection */}
              <div>
                <label className="block text-sm font-medium text-slate-900 dark:text-white mb-2">
                  Select School
                </label>
                <select
                  value={selectedSchool}
                  onChange={(e) => setSelectedSchool(e.target.value)}
                  className="w-full px-3 py-2 border border-slate-300 dark:border-slate-600 rounded-md bg-white dark:bg-slate-800 text-slate-900 dark:text-white"
                >
                  {boardingSchools.map((school) => (
                    <option key={school.id} value={school.id}>
                      {school.name} ({school.city})
                    </option>
                  ))}
                </select>
              </div>

              {/* Current Grade */}
              <div>
                <label className="block text-sm font-medium text-slate-900 dark:text-white mb-2">
                  Current Grade
                </label>
                <Input
                  type="number"
                  min="1"
                  max="12"
                  value={currentGrade}
                  onChange={(e) => setCurrentGrade(e.target.value)}
                  placeholder="e.g., 9"
                />
              </div>

              {/* Target Grade */}
              <div>
                <label className="block text-sm font-medium text-slate-900 dark:text-white mb-2">
                  Target Grade
                </label>
                <Input
                  type="number"
                  min="1"
                  max="12"
                  value={targetGrade}
                  onChange={(e) => setTargetGrade(e.target.value)}
                  placeholder="e.g., 12"
                />
              </div>

              {/* Extra Activities */}
              <div>
                <label className="block text-sm font-medium text-slate-900 dark:text-white mb-2">
                  Extra Activities Cost per Year (₹)
                </label>
                <Input
                  type="number"
                  min="0"
                  step="10000"
                  value={extraActivities}
                  onChange={(e) => setExtraActivities(e.target.value)}
                  placeholder="e.g., 50000"
                />
                <p className="text-xs text-slate-500 mt-1">Optional: Music, Art, Excursions, etc.</p>
              </div>

              {/* Extra Sports */}
              <div>
                <label className="block text-sm font-medium text-slate-900 dark:text-white mb-2">
                  Extra Sports Cost per Year (₹)
                </label>
                <Input
                  type="number"
                  min="0"
                  step="10000"
                  value={extraSports}
                  onChange={(e) => setExtraSports(e.target.value)}
                  placeholder="e.g., 30000"
                />
                <p className="text-xs text-slate-500 mt-1">Optional: Special coaching, tournaments, etc.</p>
              </div>

              {/* Download Button */}
              <Button
                onClick={handleDownload}
                className="w-full bg-blue-600 hover:bg-blue-700"
              >
                📥 Download Report
              </Button>
            </CardContent>
          </Card>

          {/* Results Section */}
          <div className="space-y-4">
            <Card className="border-2 border-blue-200 dark:border-blue-800 bg-blue-50 dark:bg-blue-900/20">
              <CardHeader>
                <CardTitle className="text-blue-900 dark:text-blue-100">
                  Cost Summary
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Years of Study */}
                <div className="flex justify-between items-center p-3 bg-white dark:bg-slate-800 rounded">
                  <span className="text-slate-600 dark:text-slate-400">Years of Study:</span>
                  <Badge variant="default">{calculation.yearsOfStudy} years</Badge>
                </div>

                {/* Annual Fee */}
                <div className="flex justify-between items-center p-3 bg-white dark:bg-slate-800 rounded">
                  <span className="text-slate-600 dark:text-slate-400">Annual Fee:</span>
                  <span className="font-semibold text-slate-900 dark:text-white">
                    ₹{(calculation.annualFee / 100000).toFixed(2)} L
                  </span>
                </div>

                {/* Total Tuition */}
                <div className="flex justify-between items-center p-3 bg-white dark:bg-slate-800 rounded">
                  <span className="text-slate-600 dark:text-slate-400">
                    Total Tuition ({calculation.yearsOfStudy} years):
                  </span>
                  <span className="font-semibold text-slate-900 dark:text-white">
                    ₹{(calculation.totalFee / 100000).toFixed(2)} L
                  </span>
                </div>

                {/* Extra Activities */}
                {calculation.extraActivities > 0 && (
                  <div className="flex justify-between items-center p-3 bg-white dark:bg-slate-800 rounded">
                    <span className="text-slate-600 dark:text-slate-400">
                      Extra Activities ({calculation.yearsOfStudy} years):
                    </span>
                    <span className="font-semibold text-yellow-600 dark:text-yellow-400">
                      ₹{(calculation.extraActivities / 100000).toFixed(2)} L
                    </span>
                  </div>
                )}

                {/* Extra Sports */}
                {calculation.extraSports > 0 && (
                  <div className="flex justify-between items-center p-3 bg-white dark:bg-slate-800 rounded">
                    <span className="text-slate-600 dark:text-slate-400">
                      Extra Sports ({calculation.yearsOfStudy} years):
                    </span>
                    <span className="font-semibold text-yellow-600 dark:text-yellow-400">
                      ₹{(calculation.extraSports / 100000).toFixed(2)} L
                    </span>
                  </div>
                )}

                {/* Grand Total */}
                <div className="flex justify-between items-center p-4 bg-blue-600 dark:bg-blue-700 rounded-lg border-2 border-blue-700">
                  <span className="font-bold text-white">GRAND TOTAL:</span>
                  <span className="font-bold text-2xl text-white">
                    ₹{(calculation.grandTotal / 100000).toFixed(2)} L
                  </span>
                </div>

                {/* Per Year Cost */}
                <div className="flex justify-between items-center p-3 bg-slate-100 dark:bg-slate-700 rounded text-sm">
                  <span className="text-slate-600 dark:text-slate-300">Average Per Year:</span>
                  <span className="font-semibold text-slate-900 dark:text-white">
                    ₹{((calculation.grandTotal / calculation.yearsOfStudy) / 100000).toFixed(2)} L
                  </span>
                </div>
              </CardContent>
            </Card>

            {/* Info Card */}
            <Card>
              <CardContent className="pt-6">
                <div className="text-sm text-slate-600 dark:text-slate-400 space-y-2">
                  <p>
                    <strong>Note:</strong> This is an approximate calculation based on average annual fees. Actual costs may vary.
                  </p>
                  <p>
                    Please contact schools for exact fees, additional charges, and payment options.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </section>
  )
}
